{% set name = "tea-tasting" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tea_tasting-{{ version }}.tar.gz
  sha256: fb076fa8619500694a43ed04a1639f926789abb679cc170a1fcc19afac26295f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - ibis-framework >=9
    - narwhals >=1.4
    - numpy >=1.25
    - pyarrow >=16
    - scipy >=1.11

test:
  imports:
    - tea_tasting
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/e10v/tea-tasting
  summary: A Python package for statistical analysis of A/B tests.
  doc_url: https://tea-tasting.e10v.me
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
