{% set name = "tea-tasting" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tea_tasting-{{ version }}.tar.gz
  sha256: db047764ddc7769491816786eb67f201d71b8ba6c5b50c068b056b28bc495339

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pdm-backend
    - pip
  run:
    - python >=3.10
    - ibis-framework >=7,<10
    - numpy >=1.25,<3
    - pandas >=2,<3
    - scipy >=1.10,<2

test:
  imports:
    - tea_tasting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/e10v/tea-tasting
  summary: A Python package for statistical analysis of A/B tests.
  doc_url: https://tea-tasting.e10v.me
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
